<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE agency [

	<!ELEMENT agency (ori)>
	<!ELEMENT ori (agency, state, division, county, offense, offender)> 

	<!ELEMENT ori (#PCDATA)>
	<!ELEMENT agency (#PCDATA)>
	<!ELEMENT state (#PCDATA)>
	<!ELEMENT division (#PCDATA)>
	<!ELEMENT county (#PCDATA)>
	<!ELEMENT offense (#PCDATA)>
	<!ELEMENT offender (#PCDATA)>

	<!ATTLIST ori id CDATA #REQUIRED>
	<!ATTLIST agency type CDATA #REQUIRED>
	<!ATTLIST state abbr CDATA #REQUIRED>
	<!ATTLIST county region CDATA #REQUIRED>
	<!ATTLIST offense name CDATA #REQUIRED>
]>



<agency>

	<ori id="TN0940100">
		<agency type="City"> Franklin</agency>
		<state abbr="tn"> Tennessee</state>
		<divison> East South</divison>
		<county region="South"> Williamson</county>
		<offense name="Theft">23D</offense>
		<offender> Building</offender>
	</ori>

	<ori id="NC0340100">
		<agency type="City">Kernersville</agency>
		<state abbr="NC">North Carolina</state>
		<divison>South Atlantic</divison>
		<county region="South">Guilford;Forsyth</county>
		<offense name="Theft">23D</offense>
	</ori>

	<ori id="NC0240500">
		<agency type="City">Whiteville</agency>
		<state abbr="NC">North Carolina</state>
		<divison>South Atlantic</divison>
		<county region="South">COLUMBUS</county>
		<offense name="Theft">23D</offense>
		<offender>Unknown</offender>	<offender>Unknown</offender>
	</ori>

	<ori id="TN0191700">
		<agency type="State University">Tenesse State University</agency>
		<state abbr="TN">Tenesse</state>
		<divison>East South</divison>
		<county region="South">Central</county>
		<offense name="Theft">23D</offense>
		<offender>Unknown</offender>
	</ori>

	<ori id="TN0790900">
		<agency type="University or College">University of Memphis</agency>
		<state abbr="TN">Tenesse</state>
		<divison>East South</divison>
		<county region="South">Central</county>
		<offense name="Theft">23D</offense>
		<offender>Unknown</offender>
	</ori>

	<ori id="MD0160400">
		<agency type="County">Montgomery</agency>
		<state abbr="MD">Maryland</state>
		<divison>South Atlantic</divison>
		<county region="South">Montgomery</county>
		<offense name="Theft">23D</offense>
		<offender>Unknown</offender>
	</ori>

	<ori id="AR0190000">
		<agency type="County">Cross</agency>
		<state abbr="AR">Arkansas</state>
		<divison>West South</divison>
		<county region="South">Cross</county>
		<offense name="Theft">23D</offense>
		<offender>Unknown</offender>
	</ori>

	<ori id="VA1020000">
		<agency type="City">Charlottesville</agency>
		<state abbr="VA">Virginia</state>
		<divison>South Atlantic</divison>
		<county region="South">Charlottesville City</county>
		<offense name="Theft">23D</offense>
		<offender>Unknown</offender>
	</ori>

	<ori id="OH0010000">
		<agency type="County">Adams</agency>
		<state abbr="OH">Ohio</state>
		<divison>East North</divison>
		<county region="Midwest">Adams</county>
		<offense name="Theft">23D</offense>
		<offender>Unknown</offender>
	</ori>

</agency>